- baseclient/ts/package.json
- baseclient/ts/src/baseclient.ts
- baseclient/ts/test/baseclient.spec.ts
add typescript’s clientbase test and code coverage
> add typescript’s clientbase test and code coverage

- .travis.yml
- baseclient/csharp/core/Credentials/AccessTokenCredential.cs
- baseclient/csharp/unitTests/Credentials/AccessTokenCredentialTest.cs
* `AccessTokenCredential` 新增 `GetHost` 方法
> supported gethost

- baseclient/csharp/core/BaseClient.cs
- baseclient/csharp/unitTests/BaseClientTest.cs
* 修改 `toQuery` 入参为 `Dictionary`
* 修改 `toJsonString` 入参为 `Dictionary`
* 修改对应的单元测试
* 重新格式化代码
> change toQuery and toJsonString

- baseclient/csharp/core/BaseClient.cs
- baseclient/csharp/unitTests/BaseClientTest.cs
* 支持默认设置 `userAgent`
* 支持自定义设置及追加 `userAgent`
* 添加对应的单元测试
> supported userAgent

- ccppath-sdk/cs/ccp-sdk.csproj
- osspath-sdk/cs/oss-sdk.csproj
> upgrade reference

- baseclient/csharp/core/BaseClient.cs
- baseclient/csharp/core/Credentials/AccessTokenCredential.cs
- baseclient/csharp/core/baseClient.csproj
- baseclient/csharp/unitTests/BaseClientTest.cs
> upgrade toJsonString

- baseclient/csharp/core/BaseClient.cs
- baseclient/csharp/unitTests/BaseClientTest.cs
* 修改 `toJsonString()` 方法返回类型为字符串
> fix toJsonString

- ccppath-sdk/cs/ccp-sdk.csproj
- osspath-sdk/cs/oss-sdk.csproj
* 将 `ccpclient` 对 `baseclient` 的引用版本改为0.0.5
* 将 `ossclient` 对 `baseclient` 的引用版本改为0.0.5
> set reference baseclient 0.0.5

- README-CN.md
- README.md
- baseclient/ts/ChangeLog.txt
- baseclient/ts/README-CN.md
- baseclient/ts/README.md
- ccppath-sdk/ts/ChangeLog.txt
- ccppath-sdk/ts/README-CN.md
- ccppath-sdk/ts/README.md
- osspath-sdk/ts/README-CN.md
- osspath-sdk/ts/README.md
> ts readme add

- README-CN.md
- README.md
- baseclient/csharp/README-CN.md
- baseclient/csharp/README.md
- ccppath-sdk/cs/README-CN.md
- ccppath-sdk/cs/README.md
- osspath-sdk/cs/README-CN.md
- osspath-sdk/cs/README.md
> fix csharp readme

- baseclient/csharp/core/BaseClient.cs
- baseclient/csharp/unitTests/BaseClientTest.cs
* 支持 `getPathName` 方法
* 增加对应的单元测试
> supported getPathName

- baseclient/csharp/core/BaseClient.cs
- baseclient/csharp/unitTests/BaseClientTest.cs
> fix getPathName

- baseclient/ts/src/baseclient.ts
- baseclient/ts/test/baseclient.spec.ts
> getPathname func and test add

- baseclient/ts/src/baseclient.ts
- baseclient/ts/test/baseclient.spec.ts
> nickname add 

- baseclient/csharp/core/BaseClient.cs
- baseclient/csharp/core/Credentials/AccessTokenCredential.cs
- baseclient/csharp/core/baseClient.csproj
- baseclient/csharp/unitTests/BaseClientTest.cs
- baseclient/csharp/unitTests/Credentials/AccessTokenCredentialTest.cs
* 支持 `nickname` 
* 修改以 `realname` 从 `config` 取值
* 修改对 `Tea` 的引用版本为 `0.0.6`
* 修改对应的单元测试
> supported nickname

- baseclient/ts/package.json
> Bump ccp-baseclient 1.1.0

- ccppath-sdk/cs/ChangeLog.md
- ccppath-sdk/cs/Properties/AssemblyInfo.cs
- ccppath-sdk/cs/ccp-sdk.csproj
- osspath-sdk/cs/ChangeLog.md
- osspath-sdk/cs/Properties/AssemblyInfo.cs
- osspath-sdk/cs/oss-sdk.csproj
* ccp first release 
* ccp-oss first release
> ccp release version 0.0.1

- baseclient/csharp/core/BaseClient.cs
- baseclient/csharp/unitTests/BaseClientTest.cs
* 修改入参 `int` 为 `int?`
* 添加对应的单元测试
> improved intNull

- baseclient/csharp/core/baseClient.csproj
> improved tea reference

- ccppath-sdk/cs/Client.cs
- ccppath-sdk/cs/ccp-sdk.csproj
- osspath-sdk/cs/Client.cs
- osspath-sdk/cs/Models/OSSDeleteFileRequest.cs
- osspath-sdk/cs/oss-sdk.csproj
* 重新生成ccp
* 修改 `C#` 版本为 5
* 修改 `CCP.BaseClient` 引用版本为 0.0.9
> regenerate ccp csharp

- .gitignore
- .travis.yml
- credential/csharp/core/Client.cs
- credential/csharp/core/Models/Config.cs
- credential/csharp/core/Properties/AssemblyInfo.cs
- credential/csharp/core/Utils/DictUtils.cs
- credential/csharp/core/Utils/Extensions.cs
- credential/csharp/core/Utils/TimeUtils.cs
- credential/csharp/core/ccp-credential.csproj
- credential/csharp/tests/ClientTest.cs
- credential/csharp/tests/Models/ConfigTest.cs
- credential/csharp/tests/Utils/DictUtilsTest.cs
- credential/csharp/tests/Utils/ExtensionsTest.cs
- credential/csharp/tests/Utils/TimeUtilsTest.cs
- credential/csharp/tests/tests.csproj
- osspath-sdk/Teafile
- osspath-sdk/java/ChangeLog.txt
- osspath-sdk/java/pom.xml
- util/csharp/core/Common.cs
- util/csharp/core/ccp-util.csproj
- util/csharp/tests/CommonTest.cs
- util/csharp/tests/Models/TestRegModel.cs
- util/csharp/tests/Models/TestRegSubModel.cs
- util/csharp/tests/tests.csproj
* 新增 `ccp-util` 项目
* 新增 `ccp-credential` 项目
> csharp supported parser2.0
